# Generated by Django 3.0 on 2020-02-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
