# Generated by Django 3.0 on 2020-02-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0004_auto_20200201_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Item',
        ),
    ]
