# Generated by Django 3.0 on 2020-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0005_auto_20200201_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_id',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
