# Generated by Django 3.0 on 2020-02-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0006_item_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_id',
        ),
    ]
