# Generated by Django 3.0 on 2020-02-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0008_auto_20200203_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
