# Generated by Django 3.0 on 2020-02-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0012_auto_20200206_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(default='SOME STRING', max_length=100)),
                ('user_last_name', models.CharField(default='SOME STRING', max_length=100)),
                ('birthday', models.DateTimeField()),
                ('user_email', models.CharField(default='SOME STRING', max_length=100)),
                ('present_location', models.CharField(default='SOME STRING', max_length=100)),
                ('user_hometown', models.CharField(default='SOME STRING', max_length=100)),
                ('user_first_language', models.CharField(default='SOME STRING', max_length=100)),
                ('user_second_language', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
    ]
