# Generated by Django 3.0 on 2020-02-09 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0013_myinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinformation',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
