# Generated by Django 3.0 on 2020-02-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0014_auto_20200209_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinformation',
            name='birthday',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
