# Generated by Django 3.0 on 2020-02-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0017_auto_20200209_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_link', models.URLField(null=True)),
                ('like_subject', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='myinformation',
            name='like_link',
        ),
        migrations.RemoveField(
            model_name='myinformation',
            name='like_subject',
        ),
    ]
