# Generated by Django 3.0 on 2020-02-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0018_auto_20200209_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='number_of_likes',
            field=models.IntegerField(null=True),
        ),
    ]
