# Generated by Django 3.0 on 2020-02-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0019_myinformation_number_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_file_load',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
