# Generated by Django 3.0 on 2020-02-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0021_auto_20200210_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_file_upload',
        ),
        migrations.AddField(
            model_name='myinformation',
            name='number_of_photos',
            field=models.IntegerField(null=True),
        ),
    ]
