# Generated by Django 3.0 on 2020-02-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0022_auto_20200211_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='number_of_posts',
            field=models.IntegerField(null=True),
        ),
    ]
