# Generated by Django 3.0 on 2020-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapps', '0024_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_post', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
